<pre>--- Summary ---
Tests passed: 0 out of 1

--- Details ---
Test #0: failed 
Test case description: World 1
Traceback:
  File "/home/tommy/Documents/OMSCS/ML4T/grading/grading.py", line 152, in proc_wrapper
    rv["output"] = func(*pos_args, **keyword_args)
  File "/home/tommy/Documents/OMSCS/ML4T/qlearning_robot/grade_robot_qlearning.py", line 216, in timeoutwrapper_nodyna
    learner = QLearner.QLearner(
  File "/home/tommy/Documents/OMSCS/ML4T/qlearning_robot/QLearner.py", line 84, in __init__
    self.q_table = np.zeroes((self.s, self.a))
  File "/home/tommy/miniconda3/envs/ml4t/lib/python3.10/site-packages/numpy/__init__.py", line 315, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'zeroes'

</pre>
